runtime: python
env: flex

# Use a special gunicorn worker class to support websockets.
entrypoint: gunicorn -b :$PORT -k flask_sockets.worker main:app

runtime_config:
  python_version: 3

# Use only a single instance, so that this local-memory-only app will work
# consistently with multiple users.
manual_scaling:
  instances: 1